@echo off
echo 🔄 Installing required packages...
pip install -r requirements.txt > nul

echo 🧪 Running tests...
pytest tests/ --html=test-report.html --self-contained-html

echo 📂 Opening test report...
start test-report.html
